#server:
#  port: 8080
mybatis-plus:
  type-aliases-package: com.nia.echoDispatch.support.domain
  configuration:
    map-underscore-to-camel-case: true # 开启下划线和驼峰映射
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/echo_dispatch?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver